name: Sphinx docs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[docs]'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build Sphinx docs and deploy to gh-pages
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: latest
          environments: dev

      - name: Build API documentation
        run: |
          pixi run -e dev sphinx-apidoc -d 2 -Mef -o docs/source/api kbws

      - name: Build HTML documentation
        run: |
          pixi run -e dev build-docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
          cname: false  # Set to your custom domain if you have one
